<a href="https://colab.research.google.com/github/PratapPawarGit/Data-Science/blob/main/Recommendation_Engine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
movies_df = pd.read_csv('Movie.csv')

In [ ]:
movies_df

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

In [ ]:
#number of unique users in the dataset
movies_df.userId.nunique()

4081

In [ ]:
movies_df.movie.unique()

array(['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)',
       'Waiting to Exhale (1995)', 'Father of the Bride Part II (1995)',
       'Heat (1995)', 'Sabrina (1995)', 'Tom and Huck (1995)',
       'Sudden Death (1995)', 'GoldenEye (1995)'], dtype=object)

In [ ]:
user_movies_df = movies_df.pivot(index='userId',
                                 columns='movie',
                                 values='rating')

In [ ]:
user_movies_df

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
userId,,,,,,,,,,
1,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
4,NaN,4.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7115,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7116,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
7117,NaN,3.0,4.0,5.0,NaN,3.0,1.0,NaN,4.0,NaN
7119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
7120,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,4.5,NaN

In [ ]:
#user_movies_df.index = movies_df.userId.unique()

In [ ]:
user_movies_df

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
userId,,,,,,,,,,
1,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
4,NaN,4.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7115,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7116,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
7117,NaN,3.0,4.0,5.0,NaN,3.0,1.0,NaN,4.0,NaN
7119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
7120,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,4.5,NaN

In [ ]:
#Impute those NaNs with 0 values
user_movies_df.fillna(0, inplace=True)

In [ ]:
user_movies_df

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
userId,,,,,,,,,,
1,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
4,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
7115,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7116,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
7117,0.0,3.0,4.0,5.0,0.0,3.0,1.0,0.0,4.0,0.0
7119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
7120,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.5,0.0

In [ ]:
#Calculating Cosine Similarity between Users
from sklearn.metrics import pairwise_distances
#from scipy.spatial.distance import cosine, correlation

In [ ]:
user_sim = 1-pairwise_distances( user_movies_df.values,metric='cosine')

In [ ]:
user_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.55337157],
       [0.        , 1.        , 0.        , ..., 0.45883147, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       ...,
       [0.        , 0.45883147, 0.45883147, ..., 1.        , 0.45883147,
        0.47607054],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       [0.55337157, 0.        , 0.62254302, ..., 0.47607054, 0.62254302,
        1.        ]], shape=(4081, 4081))

In [ ]:
#Store the results in a dataframe
user_sim_df = pd.DataFrame(user_sim)
user_sim_df

,0,1,2,3,4,5,6,7,8,9,...,4071,4072,4073,4074,4075,4076,4077,4078,4079,4080
0,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
1,0.000000,1.000000,0.000000,0.000000,0.000000,0.390567,0.707107,0.615457,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.458831,0.000000,0.000000
2,0.000000,0.000000,1.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,1.000000,0.622543
3,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.615457,0.000000,0.388514,...,0.800000,0.000000,0.000000,0.000000,0.989949,0.000000,0.000000,0.619422,0.000000,0.000000
4,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4076,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.658505,0.000000,0.000000,0.000000
4077,0.000000,0.000000,0.752577,0.000000,0.000000,0.489886,0.000000,0.370543,0.752577,0.657870,...,0.000000,0.752577,0.000000,0.532152,0.000000,0.658505,1.000000,0.345306,0.752577,0.468511
4078,0.000000,0.458831,0.458831,0.619422,0.000000,0.701884,0.567775,0.889532,0.458831,0.568212,...,0.344124,0.458831,0.000000,0.324443,0.648886,0.000000,0.345306,1.000000,0.458831,0.476071
4079,0.000000,0.000000,1.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,1.000000,0.622543
4080,0.553372,0.000000,0.622543,0.000000,0.553372,0.765455,0.391293,0.306519,0.622543,0.544201,...,0.000000,0.622543,0.553372,0.831497,0.000000,0.000000,0.468511,0.476071,0.622543,1.000000

In [ ]:
#Set the index and column names to user ids
user_sim_df.index = movies_df.userId.unique()
user_sim_df.columns = movies_df.userId.unique()

In [ ]:
user_sim_df.iloc[0:10, 0:10]

,3,6,8,10,11,12,13,14,16,19
3,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.0,1.000000,0.000000,0.000000,0.0,0.390567,0.707107,0.615457,0.000000,0.000000
8,0.0,0.000000,1.000000,0.000000,0.0,0.650945,0.000000,0.492366,1.000000,0.874157
10,0.0,0.000000,0.000000,1.000000,0.0,0.000000,0.000000,0.615457,0.000000,0.388514
11,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.0,0.390567,0.650945,0.000000,0.0,1.000000,0.736460,0.560880,0.650945,0.569028
13,0.0,0.707107,0.000000,0.000000,0.0,0.736460,1.000000,0.435194,0.000000,0.000000
14,0.0,0.615457,0.492366,0.615457,0.0,0.560880,0.435194,1.000000,0.492366,0.669519
16,0.0,0.000000,1.000000,0.000000,0.0,0.650945,0.000000,0.492366,1.000000,0.874157
19,0.0,0.000000,0.874157,0.388514,0.0,0.569028,0.000000,0.669519,0.874157,1.000000

In [ ]:
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:10, 0:10]

,3,6,8,10,11,12,13,14,16,19
3,0.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.0,0.000000,0.000000,0.000000,0.0,0.390567,0.707107,0.615457,0.000000,0.000000
8,0.0,0.000000,0.000000,0.000000,0.0,0.650945,0.000000,0.492366,1.000000,0.874157
10,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.615457,0.000000,0.388514
11,1.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.0,0.390567,0.650945,0.000000,0.0,0.000000,0.736460,0.560880,0.650945,0.569028
13,0.0,0.707107,0.000000,0.000000,0.0,0.736460,0.000000,0.435194,0.000000,0.000000
14,0.0,0.615457,0.492366,0.615457,0.0,0.560880,0.435194,0.000000,0.492366,0.669519
16,0.0,0.000000,1.000000,0.000000,0.0,0.650945,0.000000,0.492366,0.000000,0.874157
19,0.0,0.000000,0.874157,0.388514,0.0,0.569028,0.000000,0.669519,0.874157,0.000000

In [ ]:
movies_df

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

In [ ]:
#Most Similar Users

user_sim_df.idxmax(axis=1).head(20)

3       11
6      168
8       16
10    4047
11       3
12    6676
13    5953
14    4138
16       8
19    3603
22    3003
23    2096
24     539
31      66
34      93
39      53
47     258
53      39
54    2912
58       8
dtype: int64

In [ ]:
movies_df[(movies_df['userId']==3) | (movies_df['userId']==11)]

      userId             movie  rating
0          3  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
7446      11  GoldenEye (1995)     2.5

In [ ]:
user_1=movies_df[movies_df['userId']==58]

In [ ]:
user_2=movies_df[movies_df['userId']==8]

In [ ]:
user_2

      userId                    movie  rating
2          8         Toy Story (1995)     4.0
3727       8  Grumpier Old Men (1995)     5.0
5205       8              Heat (1995)     3.0
7445       8         GoldenEye (1995)     4.0

In [ ]:
user_1

      userId             movie  rating
19        58  Toy Story (1995)     5.0
5218      58       Heat (1995)     4.5

In [ ]:
pd.merge(user_1,user_2,on='movie',how='outer')

   userId_x                    movie  rating_x  userId_y  rating_y
0       NaN         GoldenEye (1995)       NaN         8       4.0
1       NaN  Grumpier Old Men (1995)       NaN         8       5.0
2      58.0              Heat (1995)       4.5         8       3.0
3      58.0         Toy Story (1995)       5.0         8       4.0

In [ ]:
def recommend_movies(user_id, user_sim_df, movies_df, num_recommendations=5):


    # Find the most similar user to the target user
    similar_users = user_sim_df.loc[user_id].sort_values(ascending=False).index[0:]  # Exclude the user itself

    # Movies rated by the target user
    movies_watched_by_user = movies_df[movies_df['userId'] == user_id]['movie'].tolist()

    # Movies watched by similar users but not by the target user
    recommendations = []
    for similar_user in similar_users:
        movies_watched_by_similar_user = movies_df[movies_df['userId'] == similar_user]['movie'].tolist()
        for movie in movies_watched_by_similar_user:
            if movie not in movies_watched_by_user and movie not in recommendations:
                recommendations.append(movie)
                if len(recommendations) == num_recommendations:
                    return recommendations
    return recommendations

In [ ]:
user_id_to_recommend = int(input("enter user id"))
recommendations = recommend_movies(user_id_to_recommend, user_sim_df, movies_df,6)
print(f"Recommended movies for user {user_id_to_recommend}: {recommendations}")

enter user id 3003

Recommended movies for user 3003: ['Father of the Bride Part II (1995)', 'Sabrina (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)', 'Tom and Huck (1995)', 'Sudden Death (1995)']

In [ ]:
recommendations

['Father of the Bride Part II (1995)',
 'Sabrina (1995)',
 'Jumanji (1995)',
 'Grumpier Old Men (1995)',
 'Tom and Huck (1995)',
 'Sudden Death (1995)']

In [ ]:
user_sim_df.loc[7].sort_values(ascending=False).index[0:]

Index([6732, 3922, 5625, 5839, 4008,  229, 7015, 5518, 2851, 3710,
       ...
          6, 5561, 1018, 5580, 5601, 5678, 5722, 5731,  821, 5557],
      dtype='int64', length=4081)

In [ ]:
movies_df[movies_df['userId'] ==5518]['movie'].tolist()

['Toy Story (1995)',
 'Jumanji (1995)',
 'Waiting to Exhale (1995)',
 'Heat (1995)',
 'GoldenEye (1995)']

In [ ]:
movies_df[movies_df['userId'] ==3922]['movie'].tolist()

['Toy Story (1995)']